### PR TITLE
Fix test rollup

### PR DESCRIPTION
**Pull request by bterlson**
fs and path are required by dotenv, so need to be declared as external.

The this-is-undefined errors are a result of TypeScript compilation and can be safely ignored.

The circular reference errors are unfortunately real, but don't seem to impact the rollup (IIUC, rollup picks some ordering which may not work properly given the circularity, but depending on usage, the circularity might not be observable). So this PR ignores those errors as well.

### CODE REVIEW

**Comment by bterlson** [comment]
Fixes #201. /cc @ramya-rao-a @ShivangiReja

**Comment by ramya-rao-a** [comment]
@btardif Where are you seeing the "this is undefined" error?
Is that related to https://github.com/Azure/azure-service-bus-node/issues/196?

**Comment by AlexGhiondea** [comment]
@bterlson I think I fixed the 'this-is-undefined' errors already.

Thanks for fixing the remaining rollup issues!!!

**Comment by bterlson** [comment]
I was getting the error with latest master. To confirm: the `this is undefined` error is fixed in master?

**Comment by bterlson** [comment]
Ok I think I know what's happening. I see that @AlexGhiondea did fix this as of 1066e2d1b, however at least e146780815e6966dfc5d0fb5d9f8d73228ad1a93 reintroduced code that shows this pattern. IMO 1066e2d1b should be reverted in favor of the ignore in this commit. It's not really realistic to avoid all patterns that result with `this` at global scope, and I really don't want to write less readable code just to make rollup happy.

**Pull request merged**
